package riptide.api.module;

public enum DisplayMode {
   DEFAULT,
   READONLY_SUMMARY,
   NUMERIC_TEXT_FIELD,
   RANGE_SLIDER,
   FILE_PICKER,
   PLAYER_NAME_LIST,
   RANK_TAG_LIST,
   PLAYER_RANK_PICKER,
   MACRO_PICKER,
   CONDITIONAL_MACRO_PICKER;
}
